version: 2.1
orbs:
  docker: circleci/docker@1.6.0

jobs:
  tests:
    docker: # executor type
      - image: nipreps/miniconda:py39_2205.0
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PAT

    environment:
      TEST_DATA_HOME: "/tmp/tests-data"

    working_directory: /tmp/tests
    steps:
      - checkout:
          path: /tmp/src/eddymotion

      - run: 
          name: Configure git (pacify datalad)
          command: |
            git config --global user.name "First Last"
            git config --global user.email "email@domain.com"

      - restore_cache:
          keys:
            - data-v1-{{ .Branch }}-{{ .Revision }}
            - data-v1--{{ .Revision }}
            - data-v1-{{ .Branch }}-
            - data-v1-main-
            - data-v1-
      - run: 
          name: Pull down test data
          command: |
            if [[ ! -d "${TEST_DATA_HOME}" ]]; then
              datalad install -rg --source=https://gin.g-node.org/nipreps-data/tests-eddymotion.git ${TEST_DATA_HOME}
            else
              cd ${TEST_DATA_HOME}
              datalad update --merge -r .
              datalad get -r -J4 *
            fi

      - save_cache:
          key: data-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - /tmp/tests-data

      - run:
          name: Initiate versioning
          command: |
            python -m pip install -U build "setuptools >= 45" wheel "setuptools_scm >= 6.2" \
                                  setuptools_scm_git_archive pip twine docutils

            pip install /tmp/src/eddymotion[all]

      - run:
          name: Run tests
          command: |
            pytest --doctest-modules /tmp/src/eddymotion/src /tmp/src/eddymotion/test

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - tests:
          filters:
            branches:
              ignore:
                - /docs?\/.*/
            tags:
              only: /.*/

  nightly:
    triggers:
      - schedule:
          cron: "0 10 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - tests
